apiVersion: apps/v1
kind: Deployment
metadata:
  name: etf-predictor-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etf-predictor
  template:
    metadata:
      labels:
        app: etf-predictor
    spec:
      containers:
      - name: streamlit-app
        image: etf-app:v1
        imagePullPolicy: IfNotPresent # Wichtig für lokale Images!
        ports:
        - containerPort: 8501
        env:
        - name: GEMINI_API_KEY
          valueFrom:
            secretKeyRef:
              name: gemini-secrets
              key: GEMINI_API_KEY